tff/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('', views.index , name='main'),
]

tff/tff/urls.py
from django.contrib import admin
from django.urls import path , include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from chat.views import chatbox

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/' , include('users.urls'), name='users'),
    path('main/' , include('main.urls'), name='main'),
    path('' , TemplateView.as_view(template_name='main/er403.html'), name='er'),
    path('chat/<str:chat_box_name>/', chatbox , name='chat'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

tff/users/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from .views import Registr
from . import views

urlpatterns = [
   path('', include('django.contrib.auth.urls')),
   path('registr/' , Registr.as_view(), name='registr'),
   path('upload_post/', views.upload_post , name='create_post')
]

tff/chat/models.py
from django.db import models

# Create your models here.

tff/main/models.py
from django.db import models

# Create your models here.

tff/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.validators import UnicodeUsernameValidator

class User(AbstractUser):
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        ("username"),
        max_length=150,
        unique=True,
        help_text=(
            "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
        ),
        validators=[username_validator],
        error_messages={
            "unique": ("A user with that username already exists."),
        },
    )
class Post(models.Model):
    text = models.TextField(max_length=2000)
    image = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    weight = models.FloatField()
    user_pop= models.ForeignKey(User , on_delete=models.CASCADE)

    def __str__(self):
        return self.text

tff/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django import forms
from .models import Post

User = get_user_model()

class UserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('id' , 'text' , 'image' ,'weight' ,   'user_pop')

tff/chat/views.py
from django.shortcuts import render

def chatbox(request, chat_box_name):
    return render(request,'chat.html', {"chat_box_name": chat_box_name})

tff/main/views.py
from django.shortcuts import render
from users.models import User , Post
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    data = Post.objects.all().select_related('user_pop')
    return render(request,'main/main.html' ,{"data":data})

tff/users/views.py
from django.shortcuts import render , redirect
from django.views import View
from .forms import UserCreationForm , PostForm
from django.contrib.auth import authenticate , login
from django.views.decorators.csrf import csrf_exempt,csrf_protect
class Registr(View):
    templates_name = 'registration/registr.html'
    def get(self, request):
        context = {
            "form":UserCreationForm()
        }
        return render(request, self.templates_name , context)
    def post(self, request):
        form = UserCreationForm(request.POST , request.FILES)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password1")
            user = authenticate(username=username , password=password)
            login(request , user)
            return redirect('login')
        
        context={
            "form":form
        }
        return render(request , self.templates_name , context)


def upload_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            post_obj = form.instance
            return render(request, 'main/upload_post.html', {post_obj:"post_obj"})
    else:
        form = PostForm()
    return render(request,  'main/upload_post.html', {'form':form})

tff/chat/templates/chat.html
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">


</head>
<div class="container">
    <h1><span class="text-danger">Внимание</span>:данный чат не сохроняет историю</h1>
</div>
<body>
    
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-6">
                <form>
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1" class="h4 pt-5">Chatbox</label>
                        <textarea class="form-control" id="chat-text" readonly rows="10"></textarea><br>
                    </div>
                    <div class="form-group">
                        <input class="form-control" placeholder="Enter text here" id="input" type="text"></br>
                    </div>
                    <input class="btn btn-primary btn-lg btn-block" id="submit" type="button" value="Send">
                </form>
            </div>
        </div>
    </div>

    {{ request.user.username|json_script:"user_username" }}
    {{ chat_box_name|json_script:"box-name" }}
    <script>
        const user_username = JSON.parse(document.getElementById('user_username').textContent);
        document.querySelector('#submit').onclick = function (e) {
            const messageInputDom = document.querySelector('#input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message,
                'username': user_username,
            }));
            messageInputDom.value = '';
        };




        const boxName = JSON.parse(document.getElementById('box-name').textContent);

        const chatSocket = new WebSocket(
            'ws://' +
            window.location.host +
            '/ws/chat/' +
            boxName +
            '/'
        );

        chatSocket.onmessage = function (e) {
            const data = JSON.parse(e.data);
            console.log(data)
            document.querySelector('#chat-text').value += (data.message + '\n' ) 
        }
    </script>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous">
    </script>
</body>

</html>

tff/main/templates/main/as401.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Для входа на сайт требуеться регистрация или авторизация</h1>
    <a href="{%url 'registr'%}">Регистрация</a>
    <br>
    <br>
    <a href="{%url 'login'%}">Вход</a>
    
</body>
</html>

tff/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%load static%}
    <link rel="stylesheet" href="{%static 'style.css'%}">
    <title>Document</title>
</head>
<body>
    <div class="wrapper">
        <header class="header">
            <div class="logo">
                <h1 class="logo_text"><a href="{%url 'main'%}">T F F</a></h1>
                <h2>ваш ник:{{user}}</h2>
            </div>
            <div class="novigations">
                <nav class="header_link">
                    {%block links%}
                    {%endblock%}
                </nav>
            </div>
        </header>
        {%block content%}
        {%endblock%}
    </div>
</body>
</html>

tff/main/templates/main/er403.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Для входа на сайт требуеться регистрация или авторизация</h1>
    <a href="{%url 'registr'%}">Регистрация</a>
    <br>
    <br>
    <a href="{%url 'login'%}">Вход</a>
    
</body>
</html>

tff/main/templates/main/main.html
{%extends 'main/base.html'%}
{%load static%}
{%block links%}
<ul>
	<li><a href="{%url 'registr'%}">Регистрация</a></li>
	<li><a href="{%url 'login'%}">Вход</a></li>
	<li><a href="{%url 'logout'%}">Выход</a></li>
	<li><a href="{%url 'create_post'%}">Создать</a></li>
</ul>
{%endblock%}
{%block content%}
<main class="main">
	<div class="container">
		{%for data in data%}
		
		<div class="carts">
			<div class="cart">
				<div class="photo">
					<img src="/media/{{data.image}}" alt="">
				</div>
				<div class="text">
					<h3>{{data.user_pop}}</h3>
					<p>{{data.text}}</p>
					<p>{{data.weight}}кг</p>
				</div>
				<div class="comunications">
					<div class="chat">
						<a href="http://127.0.0.1:8000/chat/{{user}}">
							<img src="{%static 'img/messenger.png'%}" alt="" width="30" height="30">
						</a>
					</div>
					<div class="phone">	
						<img src="{%static 'img/phone.png'%}" alt=""  width="30" height="30">
					</div>
				</div>
			</div>
		</div>
		
		{%endfor%}
		</div>
	</main>
	<footer class="footer"></footer>
{%endblock%}

tff/main/templates/main/upload_post.html
{%extends 'main/base.html'%}
{%block content%}
{% load widget_tweaks %}
<form method="post" enctype="multipart/form-data">
    
    {%csrf_token%}
    <h3>про себя {{form.text}}</h3>
    <p>Загрузите фото</p>
    {{form.image}}
    <p>Вес</p>
    {{form.weight}}
    <br>
    <br>
    <br>
    <select name="user_pop" required="" id="id_user_pop">    
        <option value="{{user.id}}">{{user}}</option>
    </select>
    
    <button type="submit">Submit</button>
</form>

{%if post_obj%}
    <h2>Succesfully uplodet {{post_obj.title}}</h2>
    <img src="{{post_obj.image.url}}" alt="concetct">
{%endif%}
{%endblock%}

tff/users/templates/upload_post.html
{%extends 'main/base.html'%}
{%block content%}
{% load widget_tweaks %}
<form method="post" enctype="multipart/form-data">
    
    {%csrf_token%}
    <h3>про себя {{form.text}}</h3>
    
    {{form.image}}
    <br>
    <br>
    <br>
    <select name="user_pop" required="" id="id_user_pop">
        <option value="1">{{user}}</option>      
      </select>
    
    <button type="submit">Submit</button>
</form>

{%if post_obj%}
    <h2>Succesfully uplodet {{post_obj.title}}</h2>
    <img src="{{post_obj.image.url}}" alt="concetct">
{%endif%}
{%endblock%}